services:
  frontend:
    container_name: math-animation-gen-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    expose:
      - 3001
    depends_on:
      - backend
    networks:
      - math-animation-gen-network
  backend:
    container_name: math-animation-gen-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8902:8902"
    expose:
      - 8902
    networks:
      - math-animation-gen-network

networks:
  math-animation-gen-network:
    name: math-animation-gen-network
